# Probabilities

For a given batch size, what is the probability that the next generated number is greater than `k`?

In [13]:
import pandas as pd
from math import comb

def calculate_combinatorial_probabilities(min_num: int, max_num: int) -> pd.DataFrame:
    data = []
    total_numbers = max_num - min_num + 1

    for k in range(min_num, max_num + 1):
        row = {}
        numbers_greater_than_k = max_num - k
        for batch_size in range(0, total_numbers + 1):
            favorable_combinations = comb(numbers_greater_than_k, batch_size)
            total_combinations = comb(total_numbers, batch_size)
            probability = favorable_combinations / total_combinations
            row[f'Batch Size {batch_size}'] = probability
        data.append(row)

    # Create a DataFrame
    df = pd.DataFrame(data, index=[f'k = {k}' for k in range(min_num, max_num + 1)])
    return df

# Parameters
min_num = 1
max_num = 10

# Generate the table
probability_table = calculate_combinatorial_probabilities(min_num, max_num)

# Display the table
probability_table.style.background_gradient(cmap='viridis', vmin=0, vmax=1)

Probability of k being